name: serentipia_gpu
channels:
  - pyg
  - defaults
dependencies:
  - python=3.10
  - seaborn
  - catboost
  - lightgbm
  - matplotlib
  - scikit-learn[version='>=1.2,<1.5']
  - tqdm
  - joblib
  - optuna
  - numpy[version='<2']
  - ninja
  - cython
  - ipykernel
  - imbalanced-learn==0.14.0
  - libstdcxx-ng
  - libgcc-ng
  - gcc_linux-64=13.1.0
  - gxx_linux-64=13.1.0
  - boost
  - boost-cpp
  - shap
  - nilearn
  - xgboost
  - typer
  - pytorch-cuda=11.8
  - protobuf
  - tabulate
  - networkx==2.6.3
prefix: /home/diego/anaconda3/envs/serentipia_gpu
