name: serentipia_gpu
channels:
  - pytorch
  - nvidia
  - conda-forge
  - pyg
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - alembic=1.16.2
  - asttokens=3.0.0
  - atk-1.0=2.36.0
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - blas=2.132
  - blas-devel=3.9.0
  - boost=1.82.0
  - boost-cpp=1.82.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.11.12
  - cairo=1.16.0
  - certifi=2025.11.12
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - click=8.2.1
  - colorama=0.4.6
  - colorlog=6.9.0
  - comm=0.2.2
  - cuda-cudart=11.8.89
  - cuda-cudart_linux-64=12.9.79
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - cuda-version=12.9
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cython=0.29.30
  - dbus=1.13.18
  - debugpy=1.8.11
  - decorator=5.2.1
  - entrypoints=0.4
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - ffmpeg=4.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gcc_impl_linux-64=13.1.0
  - gcc_linux-64=13.1.0
  - gdk-pixbuf=2.42.10
  - gettext=0.19.8.1
  - giflib=5.2.2
  - glib=2.84.2
  - glib-tools=2.84.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.6.15
  - graphite2=1.3.14
  - graphviz=2.49.0
  - greenlet=1.1.2
  - gtk2=2.24.33
  - gts=0.7.6
  - gxx_impl_linux-64=13.1.0
  - gxx_linux-64=13.1.0
  - h2=4.2.0
  - harfbuzz=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=73.1
  - idna=3.10
  - imbalanced-learn=0.14.0
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=8.37.0
  - jedi=0.19.2
  - jpeg=9e
  - jupyter_client=7.3.4
  - jupyter_core=5.8.1
  - kernel-headers_linux-64=3.10.0
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.0
  - libblas=3.9.0
  - libboost=1.82.0
  - libboost-headers=1.82.0
  - libboost-python=1.82.0
  - libboost-python-devel=1.82.0
  - libcblas=3.9.0
  - libclang13=14.0.6
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.14.1.1
  - libcups=2.4.2
  - libcurand=10.3.10.19
  - libcurl=8.12.1
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.6
  - libgcc=15.1.0
  - libgcc-devel_linux-64=13.1.0
  - libgcc-ng=15.1.0
  - libgd=2.3.3
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.84.2
  - libgomp=15.1.0
  - libhwloc=2.12.1
  - libiconv=1.17
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblightgbm=4.6.0
  - libllvm14=14.0.6
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.57.0
  - libnpp=11.8.0.86
  - libnvjpeg=11.9.0.86
  - libopenblas=0.3.30
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=3.20.3
  - librsvg=2.54.3
  - libsanitizer=13.1.0
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=13.1.0
  - libstdcxx-ng=15.1.0
  - libtasn1=4.19.0
  - libtiff=4.7.0
  - libtool=2.4.6
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxgboost=3.0.2
  - libxkbcommon=1.0.3
  - libxml2=2.13.8
  - libxslt=1.1.41
  - libzlib=1.2.13
  - lxml=4.9.1
  - lz4-c=1.9.4
  - mako=1.3.10
  - markdown-it-py=3.0.0
  - markupsafe=2.1.1
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - minizip=4.0.3
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - mysql=8.4.0
  - nccl=2.27.7.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=2.6.3
  - nibabel=5.3.2
  - nilearn=0.10.4
  - ninja=1.11.0
  - nspr=4.35
  - nss=3.89.1
  - openblas=0.3.30
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.6.0
  - optuna=4.4.0
  - pango=1.50.7
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.1.1
  - pixman=0.40.0
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - protobuf=3.20.3
  - psutil=5.9.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - py-xgboost=3.0.2
  - pycparser=2.22
  - pygments=2.19.2
  - pynndescent=0.5.13
  - pyside6=6.7.2
  - pysocks=1.7.1
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - python-graphviz=0.21
  - python_abi=3.10
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0
  - pyzmq=26.2.0
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtshadertools=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebengine=6.7.3
  - qtwebsockets=6.7.3
  - readline=8.2
  - requests=2.32.4
  - rich=14.1.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - shellingham=1.5.4
  - six=1.17.0
  - slicer=0.0.8
  - sqlalchemy=1.4.36
  - sqlite=3.46.0
  - stack_data=0.6.3
  - sysroot_linux-64=2.17
  - tabulate=0.9.0
  - tbb=2022.2.0
  - threadpoolctl=3.6.0
  - tk=8.6.14
  - tomli=2.2.1
  - tornado=6.1
  - traitlets=5.14.3
  - typer=0.16.0
  - typer-slim=0.16.0
  - typer-slim-standard=0.16.0
  - unicodedata2=14.0.0
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-renderutil=0.3.10
  - xgboost=3.0.2
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.1
      - adjusttext==1.3.0
      - bctpy==0.6.1
      - betavae-xai==0.0.0
      - betavae-xai-ad==0.1.0
      - build==1.2.2.post1
      - captum==0.8.0
      - catboost==1.2.8
      - cloudpickle==3.1.2
      - contourpy==1.3.2
      - cupy-cuda12x==13.4.1
      - dcor==0.6
      - dyconnmap==1.0.4
      - fastrlock==0.8.3
      - filelock==3.13.1
      - fonttools==4.60.1
      - fsspec==2024.6.1
      - grpcio==1.74.0
      - jinja2==3.1.4
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - lightgbm==4.6.0.99
      - llvmlite==0.46.0
      - markdown==3.8.2
      - matplotlib==3.10.7
      - narwhals==2.12.0
      - neurocombat==0.2.12
      - neurocombat-sklearn==0.1.3
      - numba==0.64.0
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.1.105
      - nvidia-nvtx-cu12==12.1.105
      - optuna-integration==4.4.0
      - packaging==26.0
      - pandas==2.3.3
      - patsy==1.0.2
      - pillow==12.0.0
      - plotly==6.5.0
      - pyparsing==3.2.5
      - pyproject-hooks==1.2.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - setuptools==80.9.0
      - shap==0.49.1
      - statsmodels==0.14.5
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchinfo==1.8.0
      - torchvision==0.20.1+cu121
      - tqdm==4.67.3
      - triton==3.1.0
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - umap-learn==0.5.3
      - vae-ad==0.1.0
      - werkzeug==3.1.3
